### ISSUE TITLE
Add custom button in default player

### ISSUE THREAD

**Issue by Rohit737-star** [THEOplayer/samples-ios-sdk#10]
Hello team,

i have an issue , i have customised my functionality with THEOplayer sdk default player screen.

i have need to add button in player screen left and right in middle of screen (center verticaly) for forward and previous video jump. i have done this in my app but when i am rotating screen in landscape with full screen my button( Previous and next ) does not appear . i have checked when clicking in full screen icon in player then player presenting new screen with same player i think this screen adding in window so my Previous and right button does not appear. 

can i easily add the previous and next button in  player screen. with sdk customised . thanks sir

**Comment by MBilliau** [comment]
Hi Rohit,

Have you followed [this](https://docs.theoplayer.com/how-to-guides/11-ui/07-how-to-insert-a-button.md#sample-resources
) guide to create additional UI elements?

Also, it would be relevant to know whether you're making use of the [allowNativeFullscreen](https://docs.theoplayer.com/faq/04-why-does-fullscreen-not-behave-as-expected-on-ios.md) property.
Is this what you mean by 'new screen'? I'm asking because the native iOS view might not allow overlaying elements.

Kind regards

**Comment by ceyhun-o** [comment]
Hi @Rohit737-star,
Since we have not heard from you for a while, we are assuming that you could solve your issue with the solution we provided and close this issue.

Feel free to open another one if you are still having problems.

Kind regards
