### ISSUE TITLE
The given license is invalid

### ISSUE THREAD

**Issue by Rohit737-star** [THEOplayer/samples-ios-sdk#16]
Hello Team,

 The given license is invalid is the message we are seeing when app is launched.

can you tell me how i can update licence without upload new build on app store.

**from documentation iOS sdk**

// passing license as a string 
let playerConfig = THEOplayerConfiguration(license: "your_license_here")
var theoplayer = THEOplayer(configuration: playerConfig)

// passing license as a URL 
let playerConfig = THEOplayerConfiguration(licenseUrl: "your_licenseUrl_here")
var theoplayer = THEOplayer(configuration: playerConfig)

question is that if we have used static licence key into app then how we can renew licence after expiry. please suggest me sir thanks

**Comment by Vini-Vijaykumar** [comment]
Hi,

Depending on your implementation, you will have to update your app. Did you use license or licenseUrl to configure your license? If these are foreign concepts, please read up on Introduction | THEOplayer Documentation  and THEOplayer/theoplayer-sdk-ios .

If you’re using license, it’s recommended to update your license value. Did you apply any whitelisting settings w.r.t. the domains? It’s possible that you get this error, because you whitelisted certain domains (e.g. Ownwebsite Sitebuilder ), but that your stream is hosted on a domain you didn’t whitelist (e.g. Get It Done Solutions ). To do this, you will have to upload a new build.

If you’re using licenseUrl, you could update your license string at this remote URL, and you wouldn’t have to upload a new build. Do note that when your licenseUrl address is unavailable, this error will also be thrown.

Thanks,
THEO Team.

**Comment by thijsl** [comment]
Hi @Rohit737-star ,

Were you able to resolve your issue?

**Comment by Rohit737-star** [comment]
sir i am using url and string licence key both. but why i am getting
INVALIDE LICENCE error in documentation simple given method so that method
i m using. let me send you whole method code.

**Comment by Rohit737-star** [comment]
Hello Team,

i was uploaded new build on app store used Licence Key and Licence URL both but after two month showing message in live build "THE GIVEN LICENCE IS INVALIDE" . Team u have replied above if we will use LICENCE_URL then not need to update Licence key . can u explain how i can make licence key permanent , i think  i need to upload new build again on app store here is my used code for Licence configuration please check.

**THEOplayerConfiguration(chromeless: false, defaultCSS: true, cssPaths: [stylePath1], jsPaths: [], jsPathsPre: [], analytics: [], pip: nil, ads: nil, ui: nil, cast: nil, hlsDateRange: nil, license: Licences.LICENCE_iPhone_SDK, licenseUrl: Licences.LICENCE_URL_iPhone, verizonMedia: nil)**

please help sir
