### ISSUE TITLE
EZDRM FairPlay custom query param

### ISSUE THREAD

**Issue by Quizer1349** [THEOplayer/samples-ios-sdk#4]
Hi guys,
I am working on FairPlay online and offline playback.

I have a list of protected HLS streams and each one should be decrypted by KSM with specific assetID and token. I tried to set `licenseAcquisitionURL` like `https://fps.ezdrm.com/api/licenses/df0XXX2-XX4d-XXX1-9XXX-1XXXXdXXb?{paramName}={token}` but decryption fails. Does SDK trim query params or something like that? Is it possible to add query param to `EzdrmDRMConfiguration` instance?

I tried before with simple AVPlayer implementation and asset resource loader delegate for FairPlay handling and it worked fine.

I used Offline_Playback project as start point.

Thanks

**Comment by savdeepgandhi13** [comment]
Hello @Quizer1349 

I understand your question and have further knowledge to share:

1. The licenseAcquisitionURL request from the player should not disregard/trims the URL supplied correctly in the source description. Can you check in the network tab if the player is making to the right URL? After connecting your phone to your computer, You can check in Safari->Develop->DeviceName->choose the right window highlighted and check in the network tab for all the calls made by player. 
2. Are you able to see the same behaviour on Web as well? Have you tried debugging or playing the streams using our Web SDK?
3. For Offline Playback- Are the streams encoded at EXT-X-Version-7 with EXT-X-SESSION-KEY tag inside the manifest URL?

Let me know the results so that I can share more details regarding the same. 

You can reach out through our Portal Service so all you related questions so that we can quickly look into your streams as well or you can reach out to your Customer Success Manager to help you raise a Service Desk Ticket for all your queries. 

Thanks 
Savdeep Singh

**Comment by Quizer1349** [comment]
Hello @savdeepgandhi13,
Thank you for your help!
 
 1. I see that SDK adds one more query param `p1=1591364920062`, looks like timestamp. Can I 
 avoid this?
 2. For now I do not use web SDK, maybe in the future.
 3. I checked master manifest and did not found those tags. But I see #EXT-X-VERSION:7  and #EXT-X-KEY tags in the manifest with chunks.

**Comment by savdeepgandhi13** [comment]
Hello @Quizer1349 

1. Can you share your streams, So that I can check as well. 
2. While you can also try to reproduce the same scenario on Web, If the player is adding something to the URL and what is the cause behind it as then the EZ DRM server should ignore the parameters irrelevant to it and return proper values. 
3. Have you tried checking with EZ DRM People as well, You can reach out to them for this issue as well see what they also share. I can share more contact details of David if required. 

Thanks 
Savdeep Singh

**Comment by Quizer1349** [comment]
1. Sorry I can’t due NDA
2. For now I can say it works without `p1` param and does not work with.
3. Managing of #EXT-X-SESSION-KEY is on EZDRM side, correct? Or on the video encoding service side (Bitmovin like)? It would be great if you'll share some contacts of EZDRM team.

Thanks!

**Comment by savdeepgandhi13** [comment]
Hello @Quizer1349 

1. It will be hard for us to look into there then, You can reachout to our Sales Team to get a NDA signed and get the support package. 
2. I can then recommend you to use our Network API to alter the request going out using THEOplayer network API (https://docs.portal.theoplayer.com/how-to-guides/08-network/01-request-response-interceptors.md#network-requestresponse-interceptors)
3. Yes, it is more on the encoding side as you will have to add that tag to your master playlist, Example would be : #EXT-X-SESSION-KEY:METHOD=SAMPLE-AES,URI="skd://fps.ezdrm.com/;09cc0377-6dd4-40cb-b09d-b582236e70fe",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"

Or you can also try to reach out to EZ DRM - David C. Eisenbacher <David.Eisenbacher@ezdrm.com> to check more on the details. 

Thanks 
Savdeep Singh
